// Generated by Snowball 2.2.0 - https://snowballstem.org/

#pragma warning disable 0164
#pragma warning disable 0162

namespace Snowball
{
    using System;
    using System.Text;
    
    ///<summary>
    ///  This class implements the stemming algorithm defined by a snowball script.
    ///  Generated by Snowball 2.2.0 - https://snowballstem.org/
    ///</summary>
    /// 
    [System.CodeDom.Compiler.GeneratedCode("Snowball", "2.2.0")]
    public partial class TamilStemmer : Stemmer
    {
        private bool B_found_vetrumai_urupu;
        private bool B_found_a_match;

        private static readonly Among[] a_0 = new[] 
        {
            new Among("\u0B95", -1, -1),
            new Among("\u0B99", -1, -1),
            new Among("\u0B9A", -1, -1),
            new Among("\u0B9E", -1, -1),
            new Among("\u0BA4", -1, -1),
            new Among("\u0BA8", -1, -1),
            new Among("\u0BAA", -1, -1),
            new Among("\u0BAE", -1, -1),
            new Among("\u0BAF", -1, -1),
            new Among("\u0BB5", -1, -1)
        };

        private static readonly Among[] a_1 = new[] 
        {
            new Among("\u0BA8\u0BCD\u0BA4", -1, -1),
            new Among("\u0BA8\u0BCD\u0BA4\u0BCD", -1, -1),
            new Among("\u0BA8\u0BCD", -1, -1)
        };

        private static readonly Among[] a_2 = new[] 
        {
            new Among("\u0BBF", -1, -1),
            new Among("\u0BC0", -1, -1),
            new Among("\u0BC8", -1, -1)
        };

        private static readonly Among[] a_3 = new[] 
        {
            new Among("\u0B95", -1, -1),
            new Among("\u0B9A", -1, -1),
            new Among("\u0B9F", -1, -1),
            new Among("\u0BA4", -1, -1),
            new Among("\u0BAA", -1, -1),
            new Among("\u0BB1", -1, -1)
        };

        private static readonly Among[] a_4 = new[] 
        {
            new Among("\u0B95", -1, -1),
            new Among("\u0B9A", -1, -1),
            new Among("\u0B9F", -1, -1),
            new Among("\u0BA4", -1, -1),
            new Among("\u0BAA", -1, -1),
            new Among("\u0BB1", -1, -1)
        };

        private static readonly Among[] a_5 = new[] 
        {
            new Among("\u0B95", -1, -1),
            new Among("\u0B9A", -1, -1),
            new Among("\u0B9F", -1, -1),
            new Among("\u0BA4", -1, -1),
            new Among("\u0BAA", -1, -1),
            new Among("\u0BB1", -1, -1)
        };

        private static readonly Among[] a_6 = new[] 
        {
            new Among("\u0BAF", -1, -1),
            new Among("\u0BB0", -1, -1),
            new Among("\u0BB2", -1, -1),
            new Among("\u0BB3", -1, -1),
            new Among("\u0BB4", -1, -1),
            new Among("\u0BB5", -1, -1)
        };

        private static readonly Among[] a_7 = new[] 
        {
            new Among("\u0B99", -1, -1),
            new Among("\u0B9E", -1, -1),
            new Among("\u0BA3", -1, -1),
            new Among("\u0BA8", -1, -1),
            new Among("\u0BA9", -1, -1),
            new Among("\u0BAE", -1, -1)
        };

        private static readonly Among[] a_8 = new[] 
        {
            new Among("\u0BAF", -1, -1),
            new Among("\u0BB5", -1, -1),
            new Among("\u0BB5\u0BCD", -1, -1)
        };

        private static readonly Among[] a_9 = new[] 
        {
            new Among("\u0BBE", -1, -1),
            new Among("\u0BBF", -1, -1),
            new Among("\u0BC0", -1, -1),
            new Among("\u0BC1", -1, -1),
            new Among("\u0BC2", -1, -1),
            new Among("\u0BC6", -1, -1),
            new Among("\u0BC7", -1, -1),
            new Among("\u0BC8", -1, -1)
        };

        private static readonly Among[] a_10 = new[] 
        {
            new Among("\u0BBE", -1, -1),
            new Among("\u0BBF", -1, -1),
            new Among("\u0BC0", -1, -1),
            new Among("\u0BC1", -1, -1),
            new Among("\u0BC2", -1, -1),
            new Among("\u0BC6", -1, -1),
            new Among("\u0BC7", -1, -1),
            new Among("\u0BC8", -1, -1)
        };

        private static readonly Among[] a_11 = new[] 
        {
            new Among("\u0B85", -1, -1),
            new Among("\u0B87", -1, -1),
            new Among("\u0B89", -1, -1)
        };

        private static readonly Among[] a_12 = new[] 
        {
            new Among("\u0B95", -1, -1),
            new Among("\u0B99", -1, -1),
            new Among("\u0B9A", -1, -1),
            new Among("\u0B9E", -1, -1),
            new Among("\u0BA4", -1, -1),
            new Among("\u0BA8", -1, -1),
            new Among("\u0BAA", -1, -1),
            new Among("\u0BAE", -1, -1),
            new Among("\u0BAF", -1, -1),
            new Among("\u0BB5", -1, -1)
        };

        private static readonly Among[] a_13 = new[] 
        {
            new Among("\u0B95", -1, -1),
            new Among("\u0B9A", -1, -1),
            new Among("\u0B9F", -1, -1),
            new Among("\u0BA4", -1, -1),
            new Among("\u0BAA", -1, -1),
            new Among("\u0BB1", -1, -1)
        };

        private static readonly Among[] a_14 = new[] 
        {
            new Among("\u0BBE", -1, -1),
            new Among("\u0BC7", -1, -1),
            new Among("\u0BCB", -1, -1)
        };

        private static readonly Among[] a_15 = new[] 
        {
            new Among("\u0BAA\u0BBF", -1, -1),
            new Among("\u0BB5\u0BBF", -1, -1)
        };

        private static readonly Among[] a_16 = new[] 
        {
            new Among("\u0BBE", -1, -1),
            new Among("\u0BBF", -1, -1),
            new Among("\u0BC0", -1, -1),
            new Among("\u0BC1", -1, -1),
            new Among("\u0BC2", -1, -1),
            new Among("\u0BC6", -1, -1),
            new Among("\u0BC7", -1, -1),
            new Among("\u0BC8", -1, -1)
        };

        private static readonly Among[] a_17 = new[] 
        {
            new Among("\u0BAA\u0B9F\u0BCD\u0B9F", -1, -1),
            new Among("\u0BAA\u0B9F\u0BCD\u0B9F\u0BA3", -1, -1),
            new Among("\u0BA4\u0BBE\u0BA9", -1, -1),
            new Among("\u0BAA\u0B9F\u0BBF\u0BA4\u0BBE\u0BA9", 2, -1),
            new Among("\u0B95\u0BC1\u0BB0\u0BBF\u0BAF", -1, -1),
            new Among("\u0BAA\u0B9F\u0BBF", -1, -1),
            new Among("\u0BAA\u0BB1\u0BCD\u0BB1\u0BBF", -1, -1),
            new Among("\u0BAA\u0B9F\u0BC1", -1, -1),
            new Among("\u0BB5\u0BBF\u0B9F\u0BC1", -1, -1),
            new Among("\u0BAA\u0B9F\u0BCD\u0B9F\u0BC1", -1, -1),
            new Among("\u0BB5\u0BBF\u0B9F\u0BCD\u0B9F\u0BC1", -1, -1),
            new Among("\u0BAA\u0B9F\u0BCD\u0B9F\u0BA4\u0BC1", -1, -1),
            new Among("\u0BC6\u0BB2\u0BCD\u0BB2\u0BBE\u0BAE\u0BCD", -1, -1)
        };

        private static readonly Among[] a_18 = new[] 
        {
            new Among("\u0B95", -1, -1),
            new Among("\u0B9A", -1, -1),
            new Among("\u0B9F", -1, -1),
            new Among("\u0BA4", -1, -1),
            new Among("\u0BAA", -1, -1),
            new Among("\u0BB1", -1, -1)
        };

        private static readonly Among[] a_19 = new[] 
        {
            new Among("\u0B95", -1, -1),
            new Among("\u0B9A", -1, -1),
            new Among("\u0B9F", -1, -1),
            new Among("\u0BA4", -1, -1),
            new Among("\u0BAA", -1, -1),
            new Among("\u0BB1", -1, -1)
        };

        private static readonly Among[] a_20 = new[] 
        {
            new Among("\u0BBE", -1, -1),
            new Among("\u0BBF", -1, -1),
            new Among("\u0BC0", -1, -1),
            new Among("\u0BC1", -1, -1),
            new Among("\u0BC2", -1, -1),
            new Among("\u0BC6", -1, -1),
            new Among("\u0BC7", -1, -1),
            new Among("\u0BC8", -1, -1)
        };

        private static readonly Among[] a_21 = new[] 
        {
            new Among("\u0BBE", -1, -1),
            new Among("\u0BBF", -1, -1),
            new Among("\u0BC0", -1, -1),
            new Among("\u0BC1", -1, -1),
            new Among("\u0BC2", -1, -1),
            new Among("\u0BC6", -1, -1),
            new Among("\u0BC7", -1, -1),
            new Among("\u0BC8", -1, -1)
        };

        private static readonly Among[] a_22 = new[] 
        {
            new Among("\u0BAA\u0B9F\u0BC1", -1, -1),
            new Among("\u0B95\u0BCA\u0BA3\u0BCD\u0B9F\u0BBF\u0BB0\u0BCD", -1, -1)
        };

        private static readonly Among[] a_23 = new[] 
        {
            new Among("\u0B85", -1, -1),
            new Among("\u0B86", -1, -1),
            new Among("\u0B87", -1, -1),
            new Among("\u0B88", -1, -1),
            new Among("\u0B89", -1, -1),
            new Among("\u0B8A", -1, -1),
            new Among("\u0B8E", -1, -1),
            new Among("\u0B8F", -1, -1),
            new Among("\u0B90", -1, -1),
            new Among("\u0B92", -1, -1),
            new Among("\u0B93", -1, -1),
            new Among("\u0B94", -1, -1)
        };

        private static readonly Among[] a_24 = new[] 
        {
            new Among("\u0BBE", -1, -1),
            new Among("\u0BBF", -1, -1),
            new Among("\u0BC0", -1, -1),
            new Among("\u0BC1", -1, -1),
            new Among("\u0BC2", -1, -1),
            new Among("\u0BC6", -1, -1),
            new Among("\u0BC7", -1, -1),
            new Among("\u0BC8", -1, -1)
        };

        private static readonly Among[] a_25 = new[] 
        {
            new Among("\u0B95\u0BBF\u0BB1", -1, -1),
            new Among("\u0B95\u0BBF\u0BA9\u0BCD\u0BB1", -1, -1),
            new Among("\u0BBE\u0BA8\u0BBF\u0BA9\u0BCD\u0BB1", -1, -1),
            new Among("\u0B95\u0BBF\u0BB1\u0BCD", -1, -1),
            new Among("\u0B95\u0BBF\u0BA9\u0BCD\u0BB1\u0BCD", -1, -1),
            new Among("\u0BBE\u0BA8\u0BBF\u0BA9\u0BCD\u0BB1\u0BCD", -1, -1)
        };



        private bool r_has_min_length()
        {
            if (!(current.Length > 4))
            {
                return false;
            }
            return true;
        }

        private bool r_fix_va_start()
        {
            {
                int c1 = cursor;
                int c2 = cursor;
                {
                    int c3 = cursor;
                    if (!(eq_s("\u0BB5\u0BCB")))
                    {
                        {
                            cursor = c3;
                            goto lab2;
                        }
                    }
                lab2: ; 
                }
                cursor = c2;
                bra = cursor;
                if (!(eq_s("\u0BB5\u0BCB")))
                {
                    goto lab1;
                }
                ket = cursor;
                slice_from("\u0B93");
                goto lab0;
            lab1: ; 
                cursor = c1;
                int c4 = cursor;
                {
                    int c5 = cursor;
                    if (!(eq_s("\u0BB5\u0BCA")))
                    {
                        {
                            cursor = c5;
                            goto lab4;
                        }
                    }
                lab4: ; 
                }
                cursor = c4;
                bra = cursor;
                if (!(eq_s("\u0BB5\u0BCA")))
                {
                    goto lab3;
                }
                ket = cursor;
                slice_from("\u0B92");
                goto lab0;
            lab3: ; 
                cursor = c1;
                int c6 = cursor;
                {
                    int c7 = cursor;
                    if (!(eq_s("\u0BB5\u0BC1")))
                    {
                        {
                            cursor = c7;
                            goto lab6;
                        }
                    }
                lab6: ; 
                }
                cursor = c6;
                bra = cursor;
                if (!(eq_s("\u0BB5\u0BC1")))
                {
                    goto lab5;
                }
                ket = cursor;
                slice_from("\u0B89");
                goto lab0;
            lab5: ; 
                cursor = c1;
                int c8 = cursor;
                {
                    int c9 = cursor;
                    if (!(eq_s("\u0BB5\u0BC2")))
                    {
                        {
                            cursor = c9;
                            goto lab7;
                        }
                    }
                lab7: ; 
                }
                cursor = c8;
                bra = cursor;
                if (!(eq_s("\u0BB5\u0BC2")))
                {
                    return false;
                }
                ket = cursor;
                slice_from("\u0B8A");
            }
        lab0: ; 
            return true;
        }

        private bool r_fix_endings()
        {
            {
                int c1 = cursor;
                while (true)
                {
                    int c2 = cursor;
                    if (!r_fix_ending())
                        goto lab1;
                    continue;
                lab1: ; 
                    cursor = c2;
                    break;
                }
                cursor = c1;
            }
            return true;
        }

        private bool r_remove_question_prefixes()
        {
            bra = cursor;
            if (!(eq_s("\u0B8E")))
            {
                return false;
            }
            if (find_among(a_0) == 0)
            {
                return false;
            }
            if (!(eq_s("\u0BCD")))
            {
                return false;
            }
            ket = cursor;
            slice_del();
            {
                int c1 = cursor;
                r_fix_va_start();
                cursor = c1;
            }
            return true;
        }

        private bool r_fix_ending()
        {
            if (!(current.Length > 3))
            {
                return false;
            }
            limit_backward = cursor;
            cursor = limit;
            {
                int c1 = limit - cursor;
                ket = cursor;
                if (find_among_b(a_1) == 0)
                {
                    goto lab1;
                }
                bra = cursor;
                slice_del();
                goto lab0;
            lab1: ; 
                cursor = limit - c1;
                ket = cursor;
                if (!(eq_s_b("\u0BAF\u0BCD")))
                {
                    goto lab2;
                }
                {
                    int c2 = limit - cursor;
                    if (find_among_b(a_2) == 0)
                    {
                        goto lab2;
                    }
                    cursor = limit - c2;
                }
                bra = cursor;
                slice_del();
                goto lab0;
            lab2: ; 
                cursor = limit - c1;
                ket = cursor;
                {
                    int c3 = limit - cursor;
                    if (!(eq_s_b("\u0B9F\u0BCD\u0BAA\u0BCD")))
                    {
                        goto lab5;
                    }
                    goto lab4;
                lab5: ; 
                    cursor = limit - c3;
                    if (!(eq_s_b("\u0B9F\u0BCD\u0B95\u0BCD")))
                    {
                        goto lab3;
                    }
                }
            lab4: ; 
                bra = cursor;
                slice_from("\u0BB3\u0BCD");
                goto lab0;
            lab3: ; 
                cursor = limit - c1;
                ket = cursor;
                if (!(eq_s_b("\u0BA9\u0BCD\u0BB1\u0BCD")))
                {
                    goto lab6;
                }
                bra = cursor;
                slice_from("\u0BB2\u0BCD");
                goto lab0;
            lab6: ; 
                cursor = limit - c1;
                ket = cursor;
                if (!(eq_s_b("\u0BB1\u0BCD\u0B95\u0BCD")))
                {
                    goto lab7;
                }
                bra = cursor;
                slice_from("\u0BB2\u0BCD");
                goto lab0;
            lab7: ; 
                cursor = limit - c1;
                ket = cursor;
                if (!(eq_s_b("\u0B9F\u0BCD\u0B9F\u0BCD")))
                {
                    goto lab8;
                }
                bra = cursor;
                slice_from("\u0B9F\u0BC1");
                goto lab0;
            lab8: ; 
                cursor = limit - c1;
                if (!(B_found_vetrumai_urupu))
                {
                    goto lab9;
                }
                ket = cursor;
                if (!(eq_s_b("\u0BA4\u0BCD\u0BA4\u0BCD")))
                {
                    goto lab9;
                }
                {
                    int c4 = limit - cursor;
                    {
                        int c5 = limit - cursor;
                        if (!(eq_s_b("\u0BC8")))
                        {
                            goto lab10;
                        }
                        goto lab9;
                    lab10: ; 
                        cursor = limit - c5;
                    }
                    cursor = limit - c4;
                }
                bra = cursor;
                slice_from("\u0BAE\u0BCD");
                bra = cursor;
                goto lab0;
            lab9: ; 
                cursor = limit - c1;
                ket = cursor;
                {
                    int c6 = limit - cursor;
                    if (!(eq_s_b("\u0BC1\u0B95\u0BCD")))
                    {
                        goto lab13;
                    }
                    goto lab12;
                lab13: ; 
                    cursor = limit - c6;
                    if (!(eq_s_b("\u0BC1\u0B95\u0BCD\u0B95\u0BCD")))
                    {
                        goto lab11;
                    }
                }
            lab12: ; 
                bra = cursor;
                slice_from("\u0BCD");
                goto lab0;
            lab11: ; 
                cursor = limit - c1;
                ket = cursor;
                if (!(eq_s_b("\u0BCD")))
                {
                    goto lab14;
                }
                if (find_among_b(a_3) == 0)
                {
                    goto lab14;
                }
                if (!(eq_s_b("\u0BCD")))
                {
                    goto lab14;
                }
                if (find_among_b(a_4) == 0)
                {
                    goto lab14;
                }
                bra = cursor;
                slice_del();
                goto lab0;
            lab14: ; 
                cursor = limit - c1;
                ket = cursor;
                if (!(eq_s_b("\u0BC1\u0B95\u0BCD")))
                {
                    goto lab15;
                }
                bra = cursor;
                slice_from("\u0BCD");
                goto lab0;
            lab15: ; 
                cursor = limit - c1;
                ket = cursor;
                if (!(eq_s_b("\u0BCD")))
                {
                    goto lab16;
                }
                if (find_among_b(a_5) == 0)
                {
                    goto lab16;
                }
                bra = cursor;
                slice_del();
                goto lab0;
            lab16: ; 
                cursor = limit - c1;
                ket = cursor;
                if (!(eq_s_b("\u0BCD")))
                {
                    goto lab17;
                }
                {
                    int c7 = limit - cursor;
                    if (find_among_b(a_6) == 0)
                    {
                        goto lab19;
                    }
                    goto lab18;
                lab19: ; 
                    cursor = limit - c7;
                    if (find_among_b(a_7) == 0)
                    {
                        goto lab17;
                    }
                }
            lab18: ; 
                if (!(eq_s_b("\u0BCD")))
                {
                    goto lab17;
                }
                bra = cursor;
                slice_from("\u0BCD");
                goto lab0;
            lab17: ; 
                cursor = limit - c1;
                ket = cursor;
                if (find_among_b(a_8) == 0)
                {
                    goto lab20;
                }
                bra = cursor;
                slice_del();
                goto lab0;
            lab20: ; 
                cursor = limit - c1;
                ket = cursor;
                if (!(eq_s_b("\u0BA9\u0BC1")))
                {
                    goto lab21;
                }
                {
                    int c8 = limit - cursor;
                    {
                        int c9 = limit - cursor;
                        if (find_among_b(a_9) == 0)
                        {
                            goto lab22;
                        }
                        goto lab21;
                    lab22: ; 
                        cursor = limit - c9;
                    }
                    cursor = limit - c8;
                }
                bra = cursor;
                slice_del();
                goto lab0;
            lab21: ; 
                cursor = limit - c1;
                ket = cursor;
                if (!(eq_s_b("\u0B99\u0BCD")))
                {
                    goto lab23;
                }
                {
                    int c10 = limit - cursor;
                    {
                        int c11 = limit - cursor;
                        if (!(eq_s_b("\u0BC8")))
                        {
                            goto lab24;
                        }
                        goto lab23;
                    lab24: ; 
                        cursor = limit - c11;
                    }
                    cursor = limit - c10;
                }
                bra = cursor;
                slice_from("\u0BAE\u0BCD");
                goto lab0;
            lab23: ; 
                cursor = limit - c1;
                ket = cursor;
                if (!(eq_s_b("\u0B99\u0BCD")))
                {
                    goto lab25;
                }
                bra = cursor;
                slice_del();
                goto lab0;
            lab25: ; 
                cursor = limit - c1;
                ket = cursor;
                if (!(eq_s_b("\u0BCD")))
                {
                    return false;
                }
                {
                    int c12 = limit - cursor;
                    {
                        int c13 = limit - cursor;
                        if (find_among_b(a_10) == 0)
                        {
                            goto lab27;
                        }
                        goto lab26;
                    lab27: ; 
                        cursor = limit - c13;
                        if (!(eq_s_b("\u0BCD")))
                        {
                            return false;
                        }
                    }
                lab26: ; 
                    cursor = limit - c12;
                }
                bra = cursor;
                slice_del();
            }
        lab0: ; 
            cursor = limit_backward;
            return true;
        }

        private bool r_remove_pronoun_prefixes()
        {
            B_found_a_match = false;
            bra = cursor;
            if (find_among(a_11) == 0)
            {
                return false;
            }
            if (find_among(a_12) == 0)
            {
                return false;
            }
            if (!(eq_s("\u0BCD")))
            {
                return false;
            }
            ket = cursor;
            slice_del();
            B_found_a_match = true;
            {
                int c1 = cursor;
                r_fix_va_start();
                cursor = c1;
            }
            return true;
        }

        private bool r_remove_plural_suffix()
        {
            B_found_a_match = false;
            limit_backward = cursor;
            cursor = limit;
            {
                int c1 = limit - cursor;
                ket = cursor;
                if (!(eq_s_b("\u0BC1\u0B99\u0BCD\u0B95\u0BB3\u0BCD")))
                {
                    goto lab1;
                }
                {
                    int c2 = limit - cursor;
                    {
                        int c3 = limit - cursor;
                        if (find_among_b(a_13) == 0)
                        {
                            goto lab2;
                        }
                        goto lab1;
                    lab2: ; 
                        cursor = limit - c3;
                    }
                    cursor = limit - c2;
                }
                bra = cursor;
                slice_from("\u0BCD");
                goto lab0;
            lab1: ; 
                cursor = limit - c1;
                ket = cursor;
                if (!(eq_s_b("\u0BB1\u0BCD\u0B95\u0BB3\u0BCD")))
                {
                    goto lab3;
                }
                bra = cursor;
                slice_from("\u0BB2\u0BCD");
                goto lab0;
            lab3: ; 
                cursor = limit - c1;
                ket = cursor;
                if (!(eq_s_b("\u0B9F\u0BCD\u0B95\u0BB3\u0BCD")))
                {
                    goto lab4;
                }
                bra = cursor;
                slice_from("\u0BB3\u0BCD");
                goto lab0;
            lab4: ; 
                cursor = limit - c1;
                ket = cursor;
                if (!(eq_s_b("\u0B95\u0BB3\u0BCD")))
                {
                    return false;
                }
                bra = cursor;
                slice_del();
            }
        lab0: ; 
            B_found_a_match = true;
            cursor = limit_backward;
            return true;
        }

        private bool r_remove_question_suffixes()
        {
            if (!r_has_min_length())
                return false;
            B_found_a_match = false;
            limit_backward = cursor;
            cursor = limit;
            {
                int c1 = limit - cursor;
                ket = cursor;
                if (find_among_b(a_14) == 0)
                {
                    goto lab0;
                }
                bra = cursor;
                slice_from("\u0BCD");
                B_found_a_match = true;
            lab0: ; 
                cursor = limit - c1;
            }
            cursor = limit_backward;
            r_fix_endings();
            return true;
        }

        private bool r_remove_command_suffixes()
        {
            if (!r_has_min_length())
                return false;
            B_found_a_match = false;
            limit_backward = cursor;
            cursor = limit;
            ket = cursor;
            if (find_among_b(a_15) == 0)
            {
                return false;
            }
            bra = cursor;
            slice_del();
            B_found_a_match = true;
            cursor = limit_backward;
            return true;
        }

        private bool r_remove_um()
        {
            B_found_a_match = false;
            if (!r_has_min_length())
                return false;
            limit_backward = cursor;
            cursor = limit;
            ket = cursor;
            if (!(eq_s_b("\u0BC1\u0BAE\u0BCD")))
            {
                return false;
            }
            bra = cursor;
            slice_from("\u0BCD");
            B_found_a_match = true;
            cursor = limit_backward;
            {
                int c1 = cursor;
                r_fix_ending();
                cursor = c1;
            }
            return true;
        }

        private bool r_remove_common_word_endings()
        {
            B_found_a_match = false;
            if (!r_has_min_length())
                return false;
            limit_backward = cursor;
            cursor = limit;
            {
                int c1 = limit - cursor;
                {
                    int c2 = limit - cursor;
                    ket = cursor;
                    {
                        int c3 = limit - cursor;
                        if (!(eq_s_b("\u0BC1\u0B9F\u0BA9\u0BCD")))
                        {
                            goto lab3;
                        }
                        goto lab2;
                    lab3: ; 
                        cursor = limit - c3;
                        if (!(eq_s_b("\u0BBF\u0BB2\u0BCD\u0BB2\u0BC8")))
                        {
                            goto lab4;
                        }
                        goto lab2;
                    lab4: ; 
                        cursor = limit - c3;
                        if (!(eq_s_b("\u0BBF\u0B9F\u0BAE\u0BCD")))
                        {
                            goto lab5;
                        }
                        goto lab2;
                    lab5: ; 
                        cursor = limit - c3;
                        if (!(eq_s_b("\u0BBF\u0BA9\u0BCD\u0BB1\u0BBF")))
                        {
                            goto lab6;
                        }
                        goto lab2;
                    lab6: ; 
                        cursor = limit - c3;
                        if (!(eq_s_b("\u0BBE\u0B95\u0BBF")))
                        {
                            goto lab7;
                        }
                        goto lab2;
                    lab7: ; 
                        cursor = limit - c3;
                        if (!(eq_s_b("\u0BBE\u0B95\u0BBF\u0BAF")))
                        {
                            goto lab8;
                        }
                        goto lab2;
                    lab8: ; 
                        cursor = limit - c3;
                        if (!(eq_s_b("\u0BC6\u0BA9\u0BCD\u0BB1\u0BC1")))
                        {
                            goto lab9;
                        }
                        goto lab2;
                    lab9: ; 
                        cursor = limit - c3;
                        if (!(eq_s_b("\u0BC1\u0BB3\u0BCD\u0BB3")))
                        {
                            goto lab10;
                        }
                        goto lab2;
                    lab10: ; 
                        cursor = limit - c3;
                        if (!(eq_s_b("\u0BC1\u0B9F\u0BC8\u0BAF")))
                        {
                            goto lab11;
                        }
                        goto lab2;
                    lab11: ; 
                        cursor = limit - c3;
                        if (!(eq_s_b("\u0BC1\u0B9F\u0BC8")))
                        {
                            goto lab12;
                        }
                        goto lab2;
                    lab12: ; 
                        cursor = limit - c3;
                        if (!(eq_s_b("\u0BC6\u0BA9\u0BC1\u0BAE\u0BCD")))
                        {
                            goto lab13;
                        }
                        goto lab2;
                    lab13: ; 
                        cursor = limit - c3;
                        if (!(eq_s_b("\u0BB2\u0BCD\u0BB2")))
                        {
                            goto lab14;
                        }
                        {
                            int c4 = limit - cursor;
                            {
                                int c5 = limit - cursor;
                                if (find_among_b(a_16) == 0)
                                {
                                    goto lab15;
                                }
                                goto lab14;
                            lab15: ; 
                                cursor = limit - c5;
                            }
                            cursor = limit - c4;
                        }
                        goto lab2;
                    lab14: ; 
                        cursor = limit - c3;
                        if (!(eq_s_b("\u0BC6\u0BA9")))
                        {
                            goto lab16;
                        }
                        goto lab2;
                    lab16: ; 
                        cursor = limit - c3;
                        if (!(eq_s_b("\u0BBE\u0B95\u0BBF")))
                        {
                            goto lab1;
                        }
                    }
                lab2: ; 
                    bra = cursor;
                    slice_from("\u0BCD");
                    B_found_a_match = true;
                    cursor = limit - c2;
                }
                goto lab0;
            lab1: ; 
                cursor = limit - c1;
                {
                    int c6 = limit - cursor;
                    ket = cursor;
                    if (find_among_b(a_17) == 0)
                    {
                        return false;
                    }
                    bra = cursor;
                    slice_del();
                    B_found_a_match = true;
                    cursor = limit - c6;
                }
            }
        lab0: ; 
            cursor = limit_backward;
            r_fix_endings();
            return true;
        }

        private bool r_remove_vetrumai_urupukal()
        {
            B_found_a_match = false;
            B_found_vetrumai_urupu = false;
            if (!r_has_min_length())
                return false;
            limit_backward = cursor;
            cursor = limit;
            {
                int c1 = limit - cursor;
                {
                    int c2 = limit - cursor;
                    ket = cursor;
                    if (!(eq_s_b("\u0BA9\u0BC8")))
                    {
                        goto lab1;
                    }
                    bra = cursor;
                    slice_del();
                    cursor = limit - c2;
                }
                goto lab0;
            lab1: ; 
                cursor = limit - c1;
                {
                    int c3 = limit - cursor;
                    ket = cursor;
                    {
                        int c4 = limit - cursor;
                        {
                            int c5 = limit - cursor;
                            if (!(eq_s_b("\u0BBF\u0BA9\u0BC8")))
                            {
                                goto lab6;
                            }
                            goto lab5;
                        lab6: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BC8")))
                            {
                                goto lab4;
                            }
                        }
                    lab5: ; 
                        {
                            int c6 = limit - cursor;
                            {
                                int c7 = limit - cursor;
                                if (find_among_b(a_18) == 0)
                                {
                                    goto lab7;
                                }
                                goto lab4;
                            lab7: ; 
                                cursor = limit - c7;
                            }
                            cursor = limit - c6;
                        }
                        goto lab3;
                    lab4: ; 
                        cursor = limit - c4;
                        if (!(eq_s_b("\u0BC8")))
                        {
                            goto lab2;
                        }
                        {
                            int c8 = limit - cursor;
                            if (find_among_b(a_19) == 0)
                            {
                                goto lab2;
                            }
                            if (!(eq_s_b("\u0BCD")))
                            {
                                goto lab2;
                            }
                            cursor = limit - c8;
                        }
                    }
                lab3: ; 
                    bra = cursor;
                    slice_from("\u0BCD");
                    cursor = limit - c3;
                }
                goto lab0;
            lab2: ; 
                cursor = limit - c1;
                {
                    int c9 = limit - cursor;
                    ket = cursor;
                    {
                        int c10 = limit - cursor;
                        if (!(eq_s_b("\u0BCA\u0B9F\u0BC1")))
                        {
                            goto lab10;
                        }
                        goto lab9;
                    lab10: ; 
                        cursor = limit - c10;
                        if (!(eq_s_b("\u0BCB\u0B9F\u0BC1")))
                        {
                            goto lab11;
                        }
                        goto lab9;
                    lab11: ; 
                        cursor = limit - c10;
                        if (!(eq_s_b("\u0BBF\u0BB2\u0BCD")))
                        {
                            goto lab12;
                        }
                        goto lab9;
                    lab12: ; 
                        cursor = limit - c10;
                        if (!(eq_s_b("\u0BBF\u0BB1\u0BCD")))
                        {
                            goto lab13;
                        }
                        goto lab9;
                    lab13: ; 
                        cursor = limit - c10;
                        if (!(eq_s_b("\u0BBF\u0BA9\u0BCD")))
                        {
                            goto lab14;
                        }
                        {
                            int c11 = limit - cursor;
                            {
                                int c12 = limit - cursor;
                                if (!(eq_s_b("\u0BAE")))
                                {
                                    goto lab15;
                                }
                                goto lab14;
                            lab15: ; 
                                cursor = limit - c12;
                            }
                            cursor = limit - c11;
                        }
                        goto lab9;
                    lab14: ; 
                        cursor = limit - c10;
                        if (!(eq_s_b("\u0BBF\u0BA9\u0BCD\u0BB1\u0BC1")))
                        {
                            goto lab16;
                        }
                        goto lab9;
                    lab16: ; 
                        cursor = limit - c10;
                        if (!(eq_s_b("\u0BBF\u0BB0\u0BC1\u0BA8\u0BCD\u0BA4\u0BC1")))
                        {
                            goto lab17;
                        }
                        goto lab9;
                    lab17: ; 
                        cursor = limit - c10;
                        if (!(eq_s_b("\u0BB5\u0BBF\u0B9F")))
                        {
                            goto lab18;
                        }
                        goto lab9;
                    lab18: ; 
                        cursor = limit - c10;
                        if (!(current.Length >= 7))
                        {
                            goto lab19;
                        }
                        if (!(eq_s_b("\u0BBF\u0B9F\u0BAE\u0BCD")))
                        {
                            goto lab19;
                        }
                        goto lab9;
                    lab19: ; 
                        cursor = limit - c10;
                        if (!(eq_s_b("\u0BBE\u0BB2\u0BCD")))
                        {
                            goto lab20;
                        }
                        goto lab9;
                    lab20: ; 
                        cursor = limit - c10;
                        if (!(eq_s_b("\u0BC1\u0B9F\u0BC8")))
                        {
                            goto lab21;
                        }
                        goto lab9;
                    lab21: ; 
                        cursor = limit - c10;
                        if (!(eq_s_b("\u0BBE\u0BAE\u0BB2\u0BCD")))
                        {
                            goto lab22;
                        }
                        goto lab9;
                    lab22: ; 
                        cursor = limit - c10;
                        if (!(eq_s_b("\u0BB2\u0BCD")))
                        {
                            goto lab23;
                        }
                        {
                            int c13 = limit - cursor;
                            {
                                int c14 = limit - cursor;
                                if (find_among_b(a_20) == 0)
                                {
                                    goto lab24;
                                }
                                goto lab23;
                            lab24: ; 
                                cursor = limit - c14;
                            }
                            cursor = limit - c13;
                        }
                        goto lab9;
                    lab23: ; 
                        cursor = limit - c10;
                        if (!(eq_s_b("\u0BC1\u0BB3\u0BCD")))
                        {
                            goto lab8;
                        }
                    }
                lab9: ; 
                    bra = cursor;
                    slice_from("\u0BCD");
                    cursor = limit - c9;
                }
                goto lab0;
            lab8: ; 
                cursor = limit - c1;
                {
                    int c15 = limit - cursor;
                    ket = cursor;
                    {
                        int c16 = limit - cursor;
                        if (!(eq_s_b("\u0B95\u0BA3\u0BCD")))
                        {
                            goto lab27;
                        }
                        goto lab26;
                    lab27: ; 
                        cursor = limit - c16;
                        if (!(eq_s_b("\u0BAE\u0BC1\u0BA9\u0BCD")))
                        {
                            goto lab28;
                        }
                        goto lab26;
                    lab28: ; 
                        cursor = limit - c16;
                        if (!(eq_s_b("\u0BAE\u0BC7\u0BB2\u0BCD")))
                        {
                            goto lab29;
                        }
                        goto lab26;
                    lab29: ; 
                        cursor = limit - c16;
                        if (!(eq_s_b("\u0BAE\u0BC7\u0BB1\u0BCD")))
                        {
                            goto lab30;
                        }
                        goto lab26;
                    lab30: ; 
                        cursor = limit - c16;
                        if (!(eq_s_b("\u0B95\u0BC0\u0BB4\u0BCD")))
                        {
                            goto lab31;
                        }
                        goto lab26;
                    lab31: ; 
                        cursor = limit - c16;
                        if (!(eq_s_b("\u0BAA\u0BBF\u0BA9\u0BCD")))
                        {
                            goto lab32;
                        }
                        goto lab26;
                    lab32: ; 
                        cursor = limit - c16;
                        if (!(eq_s_b("\u0BA4\u0BC1")))
                        {
                            goto lab25;
                        }
                        {
                            int c17 = limit - cursor;
                            {
                                int c18 = limit - cursor;
                                if (find_among_b(a_21) == 0)
                                {
                                    goto lab33;
                                }
                                goto lab25;
                            lab33: ; 
                                cursor = limit - c18;
                            }
                            cursor = limit - c17;
                        }
                    }
                lab26: ; 
                    bra = cursor;
                    slice_del();
                    cursor = limit - c15;
                }
                goto lab0;
            lab25: ; 
                cursor = limit - c1;
                {
                    int c19 = limit - cursor;
                    ket = cursor;
                    if (!(eq_s_b("\u0BC0")))
                    {
                        return false;
                    }
                    bra = cursor;
                    slice_from("\u0BBF");
                    cursor = limit - c19;
                }
            }
        lab0: ; 
            B_found_a_match = true;
            B_found_vetrumai_urupu = true;
            {
                int c20 = limit - cursor;
                ket = cursor;
                if (!(eq_s_b("\u0BBF\u0BA9\u0BCD")))
                {
                    goto lab34;
                }
                bra = cursor;
                slice_from("\u0BCD");
            lab34: ; 
                cursor = limit - c20;
            }
            cursor = limit_backward;
            r_fix_endings();
            return true;
        }

        private bool r_remove_tense_suffixes()
        {
            B_found_a_match = true;
            while (true)
            {
                int c1 = cursor;
                if (!(B_found_a_match))
                {
                    goto lab0;
                }
                {
                    int c2 = cursor;
                    r_remove_tense_suffix();
                    cursor = c2;
                }
                continue;
            lab0: ; 
                cursor = c1;
                break;
            }
            return true;
        }

        private bool r_remove_tense_suffix()
        {
            B_found_a_match = false;
            if (!r_has_min_length())
                return false;
            limit_backward = cursor;
            cursor = limit;
            {
                int c1 = limit - cursor;
                {
                    int c2 = limit - cursor;
                    {
                        int c3 = limit - cursor;
                        ket = cursor;
                        if (find_among_b(a_22) == 0)
                        {
                            goto lab2;
                        }
                        bra = cursor;
                        slice_del();
                        B_found_a_match = true;
                        cursor = limit - c3;
                    }
                    goto lab1;
                lab2: ; 
                    cursor = limit - c2;
                    {
                        int c4 = limit - cursor;
                        ket = cursor;
                        {
                            int c5 = limit - cursor;
                            if (!(eq_s_b("\u0BAE\u0BBE\u0BB0\u0BCD")))
                            {
                                goto lab5;
                            }
                            goto lab4;
                        lab5: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BAE\u0BBF\u0BA9\u0BCD")))
                            {
                                goto lab6;
                            }
                            goto lab4;
                        lab6: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BA9\u0BA9\u0BCD")))
                            {
                                goto lab7;
                            }
                            goto lab4;
                        lab7: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BA9\u0BBE\u0BA9\u0BCD")))
                            {
                                goto lab8;
                            }
                            goto lab4;
                        lab8: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BA9\u0BBE\u0BB3\u0BCD")))
                            {
                                goto lab9;
                            }
                            goto lab4;
                        lab9: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BA9\u0BBE\u0BB0\u0BCD")))
                            {
                                goto lab10;
                            }
                            goto lab4;
                        lab10: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BB5\u0BA9\u0BCD")))
                            {
                                goto lab11;
                            }
                            {
                                int c6 = limit - cursor;
                                {
                                    int c7 = limit - cursor;
                                    if (find_among_b(a_23) == 0)
                                    {
                                        goto lab12;
                                    }
                                    goto lab11;
                                lab12: ; 
                                    cursor = limit - c7;
                                }
                                cursor = limit - c6;
                            }
                            goto lab4;
                        lab11: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BA9\u0BB3\u0BCD")))
                            {
                                goto lab13;
                            }
                            goto lab4;
                        lab13: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BB5\u0BB3\u0BCD")))
                            {
                                goto lab14;
                            }
                            goto lab4;
                        lab14: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BA9\u0BB0\u0BCD")))
                            {
                                goto lab15;
                            }
                            goto lab4;
                        lab15: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BB5\u0BB0\u0BCD")))
                            {
                                goto lab16;
                            }
                            goto lab4;
                        lab16: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BA9")))
                            {
                                goto lab17;
                            }
                            goto lab4;
                        lab17: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BAA")))
                            {
                                goto lab18;
                            }
                            goto lab4;
                        lab18: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0B95")))
                            {
                                goto lab19;
                            }
                            goto lab4;
                        lab19: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BA4")))
                            {
                                goto lab20;
                            }
                            goto lab4;
                        lab20: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BAF")))
                            {
                                goto lab21;
                            }
                            goto lab4;
                        lab21: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BAA\u0BA9\u0BCD")))
                            {
                                goto lab22;
                            }
                            goto lab4;
                        lab22: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BAA\u0BB3\u0BCD")))
                            {
                                goto lab23;
                            }
                            goto lab4;
                        lab23: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BAA\u0BB0\u0BCD")))
                            {
                                goto lab24;
                            }
                            goto lab4;
                        lab24: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BA4\u0BC1")))
                            {
                                goto lab25;
                            }
                            {
                                int c8 = limit - cursor;
                                {
                                    int c9 = limit - cursor;
                                    if (find_among_b(a_24) == 0)
                                    {
                                        goto lab26;
                                    }
                                    goto lab25;
                                lab26: ; 
                                    cursor = limit - c9;
                                }
                                cursor = limit - c8;
                            }
                            goto lab4;
                        lab25: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BBF\u0BB1\u0BCD\u0BB1\u0BC1")))
                            {
                                goto lab27;
                            }
                            goto lab4;
                        lab27: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BAA\u0BAE\u0BCD")))
                            {
                                goto lab28;
                            }
                            goto lab4;
                        lab28: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BA9\u0BAE\u0BCD")))
                            {
                                goto lab29;
                            }
                            goto lab4;
                        lab29: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BA4\u0BC1\u0BAE\u0BCD")))
                            {
                                goto lab30;
                            }
                            goto lab4;
                        lab30: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BB1\u0BC1\u0BAE\u0BCD")))
                            {
                                goto lab31;
                            }
                            goto lab4;
                        lab31: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0B95\u0BC1\u0BAE\u0BCD")))
                            {
                                goto lab32;
                            }
                            goto lab4;
                        lab32: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BA9\u0BC6\u0BA9\u0BCD")))
                            {
                                goto lab33;
                            }
                            goto lab4;
                        lab33: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BA9\u0BC8")))
                            {
                                goto lab34;
                            }
                            goto lab4;
                        lab34: ; 
                            cursor = limit - c5;
                            if (!(eq_s_b("\u0BB5\u0BC8")))
                            {
                                goto lab3;
                            }
                        }
                    lab4: ; 
                        bra = cursor;
                        slice_del();
                        B_found_a_match = true;
                        cursor = limit - c4;
                    }
                    goto lab1;
                lab3: ; 
                    cursor = limit - c2;
                    {
                        int c10 = limit - cursor;
                        ket = cursor;
                        {
                            int c11 = limit - cursor;
                            if (!(eq_s_b("\u0BBE\u0BA9\u0BCD")))
                            {
                                goto lab37;
                            }
                            {
                                int c12 = limit - cursor;
                                {
                                    int c13 = limit - cursor;
                                    if (!(eq_s_b("\u0B9A")))
                                    {
                                        goto lab38;
                                    }
                                    goto lab37;
                                lab38: ; 
                                    cursor = limit - c13;
                                }
                                cursor = limit - c12;
                            }
                            goto lab36;
                        lab37: ; 
                            cursor = limit - c11;
                            if (!(eq_s_b("\u0BBE\u0BB3\u0BCD")))
                            {
                                goto lab39;
                            }
                            goto lab36;
                        lab39: ; 
                            cursor = limit - c11;
                            if (!(eq_s_b("\u0BBE\u0BB0\u0BCD")))
                            {
                                goto lab40;
                            }
                            goto lab36;
                        lab40: ; 
                            cursor = limit - c11;
                            if (!(eq_s_b("\u0BC7\u0BA9\u0BCD")))
                            {
                                goto lab41;
                            }
                            goto lab36;
                        lab41: ; 
                            cursor = limit - c11;
                            if (!(eq_s_b("\u0BBE")))
                            {
                                goto lab42;
                            }
                            goto lab36;
                        lab42: ; 
                            cursor = limit - c11;
                            if (!(eq_s_b("\u0BBE\u0BAE\u0BCD")))
                            {
                                goto lab43;
                            }
                            goto lab36;
                        lab43: ; 
                            cursor = limit - c11;
                            if (!(eq_s_b("\u0BC6\u0BAE\u0BCD")))
                            {
                                goto lab44;
                            }
                            goto lab36;
                        lab44: ; 
                            cursor = limit - c11;
                            if (!(eq_s_b("\u0BC7\u0BAE\u0BCD")))
                            {
                                goto lab45;
                            }
                            goto lab36;
                        lab45: ; 
                            cursor = limit - c11;
                            if (!(eq_s_b("\u0BCB\u0BAE\u0BCD")))
                            {
                                goto lab46;
                            }
                            goto lab36;
                        lab46: ; 
                            cursor = limit - c11;
                            if (!(eq_s_b("\u0B95\u0BC1\u0BAE\u0BCD")))
                            {
                                goto lab47;
                            }
                            goto lab36;
                        lab47: ; 
                            cursor = limit - c11;
                            if (!(eq_s_b("\u0BA4\u0BC1\u0BAE\u0BCD")))
                            {
                                goto lab48;
                            }
                            goto lab36;
                        lab48: ; 
                            cursor = limit - c11;
                            if (!(eq_s_b("\u0B9F\u0BC1\u0BAE\u0BCD")))
                            {
                                goto lab49;
                            }
                            goto lab36;
                        lab49: ; 
                            cursor = limit - c11;
                            if (!(eq_s_b("\u0BB1\u0BC1\u0BAE\u0BCD")))
                            {
                                goto lab50;
                            }
                            goto lab36;
                        lab50: ; 
                            cursor = limit - c11;
                            if (!(eq_s_b("\u0BBE\u0BAF\u0BCD")))
                            {
                                goto lab51;
                            }
                            goto lab36;
                        lab51: ; 
                            cursor = limit - c11;
                            if (!(eq_s_b("\u0BA9\u0BC6\u0BA9\u0BCD")))
                            {
                                goto lab52;
                            }
                            goto lab36;
                        lab52: ; 
                            cursor = limit - c11;
                            if (!(eq_s_b("\u0BA9\u0BBF\u0BB0\u0BCD")))
                            {
                                goto lab53;
                            }
                            goto lab36;
                        lab53: ; 
                            cursor = limit - c11;
                            if (!(eq_s_b("\u0BC0\u0BB0\u0BCD")))
                            {
                                goto lab54;
                            }
                            goto lab36;
                        lab54: ; 
                            cursor = limit - c11;
                            if (!(eq_s_b("\u0BC0\u0BAF\u0BB0\u0BCD")))
                            {
                                goto lab35;
                            }
                        }
                    lab36: ; 
                        bra = cursor;
                        slice_from("\u0BCD");
                        B_found_a_match = true;
                        cursor = limit - c10;
                    }
                    goto lab1;
                lab35: ; 
                    cursor = limit - c2;
                    {
                        int c14 = limit - cursor;
                        ket = cursor;
                        {
                            int c15 = limit - cursor;
                            if (!(eq_s_b("\u0B95\u0BC1")))
                            {
                                goto lab56;
                            }
                            goto lab55;
                        lab56: ; 
                            cursor = limit - c15;
                            if (!(eq_s_b("\u0BA4\u0BC1")))
                            {
                                goto lab0;
                            }
                        }
                    lab55: ; 
                        {
                            int c16 = limit - cursor;
                            if (!(eq_s_b("\u0BCD")))
                            {
                                goto lab0;
                            }
                            cursor = limit - c16;
                        }
                        bra = cursor;
                        slice_del();
                        B_found_a_match = true;
                        cursor = limit - c14;
                    }
                }
            lab1: ; 
            lab0: ; 
                cursor = limit - c1;
            }
            {
                int c17 = limit - cursor;
                ket = cursor;
                if (find_among_b(a_25) == 0)
                {
                    goto lab57;
                }
                bra = cursor;
                slice_del();
                B_found_a_match = true;
            lab57: ; 
                cursor = limit - c17;
            }
            cursor = limit_backward;
            r_fix_endings();
            return true;
        }

        protected override bool stem()
        {
            B_found_vetrumai_urupu = false;
            {
                int c1 = cursor;
                r_fix_ending();
                cursor = c1;
            }
            if (!r_has_min_length())
                return false;
            {
                int c2 = cursor;
                r_remove_question_prefixes();
                cursor = c2;
            }
            {
                int c3 = cursor;
                r_remove_pronoun_prefixes();
                cursor = c3;
            }
            {
                int c4 = cursor;
                r_remove_question_suffixes();
                cursor = c4;
            }
            {
                int c5 = cursor;
                r_remove_um();
                cursor = c5;
            }
            {
                int c6 = cursor;
                r_remove_common_word_endings();
                cursor = c6;
            }
            {
                int c7 = cursor;
                r_remove_vetrumai_urupukal();
                cursor = c7;
            }
            {
                int c8 = cursor;
                r_remove_plural_suffix();
                cursor = c8;
            }
            {
                int c9 = cursor;
                r_remove_command_suffixes();
                cursor = c9;
            }
            {
                int c10 = cursor;
                r_remove_tense_suffixes();
                cursor = c10;
            }
            return true;
        }

    }
}

