name: CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v3

    - name: Get .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.*'

    - name: Publish
      run: |
        cd src/issuesof.net
        dotnet publish -c Release /p:SourceRevisionId=${{ github.sha }} -o '../../artifacts/issuesof.net'
        cd ../..

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: issuesofdotnet
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
        package: ./artifacts/issuesof.net

