name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v3

    - name: Get .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.*'

    - name: Build
      run: |
        cd src/issuesof.net
        dotnet build -c Release -o '../../artifacts/issuesof.net'
        cd ../..
